services:
  maildev:
    image: maildev/maildev:latest
    container_name: stampee-maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - MAILDEV_INCOMING_USER=
      - MAILDEV_INCOMING_PASS=
    restart: unless-stopped

  clamav:
    platform: linux/x86_64
    image: clamav/clamav:latest
    container_name: stampee-clamav
    ports:
      - "3310:3310"
    volumes:
      - clamav-data:/var/lib/clamav
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "clamdscan", "--ping", "1"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.4
    container_name: stampee-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=stampee_root
      - MYSQL_DATABASE=stampee
      - MYSQL_USER=stampee
      - MYSQL_PASSWORD=stampee
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: stampee-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

  redis:
    image: redis:7-alpine
    container_name: stampee-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: stampee-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APP_NAME=stampee-tech-assignement
      - APP_BASE_URL=http://localhost:3000
      - DEFAULT_SENDER_EMAIL=no-reply@stampee-tech-assignement.test
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=stampee
      - DB_PASSWORD=stampee
      - DB_NAME=stampee
      - DB_SYNC=true
      - DB_TEST_HOST=mysql
      - DB_TEST_PORT=3306
      - DB_TEST_USER=stampee
      - DB_TEST_PASSWORD=stampee
      - DB_TEST_NAME=stampee_test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMTP_HOST=maildev
      - SMTP_PORT=1025
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
      - STORAGE_PATH=/app/backend/uploads
      - MAX_FILES_PER_MESSAGE=10
      - MAX_TOTAL_UPLOAD_BYTES=268435456
      - DOWNLOAD_TTL_HOURS=48
    volumes:
      - ./backend:/app/backend
      - ./backend/uploads:/app/backend/uploads
      - /app/backend/node_modules
      - /app/node_modules
    depends_on:
      - maildev
      - clamav
      - mysql
      - redis
    command: pnpm dev
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: stampee-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3000/api
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/node_modules
    command: pnpm dev:frontend
    restart: unless-stopped

volumes:
  clamav-data:
  mysql-data:
